<?php
/** @var Attributes $block */
?>
<div class='product-description'>
    <?php if ($attributes = $block->getThreeAttributes()): ?>
        <ul>
            <?php foreach ($attributes as $a): ?>
                <li>
                    <b><?= $a['value']; ?>:</b> <?= $a['label']; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <?php if ($description = $block->getProduct()->getShortDescription()): ?>
        <div class='short-description'>
            <?= $description; ?>
        </div>
    <?php endif; ?>
</div>

